import { Raleway, Lora, Victor_Mono } from "next/font/google";
import type { Metadata } from "next";
import { ThemeWrapper } from "@/components/theme-wrapper";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { NavBar } from "@/components/navbar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
});

const victorMono = Victor_Mono({
  variable: "--font-victor-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${lora.variable} ${victorMono.variable} antialiased`}
      >
        <ThemeWrapper>
          <div className="sticky top-0 z-50">
            <NavBar />
          </div>
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
